variable "VPC_CIDR" {}
variable "ENV" {}
variable "AZ" {}
variable "PUBLIC_SUBNET_CIDR" {}
variable "PRIVATE_SUBNET_CIDR" {}
variable "DEFAULT_VPC_ID" {}
variable "DEFAULT_VPC_CIDR" {}
variable "DEFAULT_VPC_RT" {}
variable "HOSTEDZONE_PRIVATE_ID" {}
variable "HOSTEDZONE_PRIVATE_NAME" {}
variable "HOSTEDZONE_PUBLIC_ID" {}
variable "HOSTEDZONE_PUBLIC_NAME" {}